# .github/workflows/snake.yml
name: Generate Snake

# 1) explizit Schreibrechte für contents setzen
permissions:
  contents: write

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # 2) Platane/snk@v3 für das "Snake"-GIF/SVG
      - uses: Platane/snk@v3
        with:
          github_user_name: mishmanners
          outputs: |
            dist/github-contribution-grid-snake.gif
            dist/github-contribution-grid-snake.svg

      - run: git status

      # 3) Push-Step: „token:“ statt „github_token:“
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
