# .github/workflows/snake.yml
name: Generate Snake

on:
  schedule:
    # Läuft alle 6 Stunden
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Platane/snk in Version v3 nutzen – hier wird das „outputs“-Feld verwendet,
      # wodurch die alten set-output-Aufrufe wegfallen.
      - uses: Platane/snk@v3
        with:
          github_user_name: mishmanners
          outputs: |
            dist/github-contribution-grid-snake.gif
            dist/github-contribution-grid-snake.svg

      - run: git status

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
